var wms_layers = [];

var format_ADMINISTRASI_LN_25K_0 = new ol.format.GeoJSON();
var features_ADMINISTRASI_LN_25K_0 = format_ADMINISTRASI_LN_25K_0.readFeatures(json_ADMINISTRASI_LN_25K_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ADMINISTRASI_LN_25K_0 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ADMINISTRASI_LN_25K_0.addFeatures(features_ADMINISTRASI_LN_25K_0);
var lyr_ADMINISTRASI_LN_25K_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ADMINISTRASI_LN_25K_0, 
                style: style_ADMINISTRASI_LN_25K_0,
                interactive: true,
                title: '<img src="styles/legend/ADMINISTRASI_LN_25K_0.png" /> ADMINISTRASI_LN_25K'
            });
var format_ADMINISTRASIDESA_AR_25K_1 = new ol.format.GeoJSON();
var features_ADMINISTRASIDESA_AR_25K_1 = format_ADMINISTRASIDESA_AR_25K_1.readFeatures(json_ADMINISTRASIDESA_AR_25K_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ADMINISTRASIDESA_AR_25K_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ADMINISTRASIDESA_AR_25K_1.addFeatures(features_ADMINISTRASIDESA_AR_25K_1);
var lyr_ADMINISTRASIDESA_AR_25K_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ADMINISTRASIDESA_AR_25K_1, 
                style: style_ADMINISTRASIDESA_AR_25K_1,
                interactive: true,
    title: 'ADMINISTRASIDESA_AR_25K<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_0.png" /> ampungkelor<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_1.png" /> Ancolpasir<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_2.png" /> Babakan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_3.png" /> Babakanasem<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_4.png" /> Babat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_5.png" /> Badakanom<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_6.png" /> Bakung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_7.png" /> Balaraja<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_8.png" /> Bantarpanjang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_9.png" /> Banyuasih<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_10.png" /> Batok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_11.png" /> Belimbing<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_12.png" /> Bencongan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_13.png" /> Bencongan Indah<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_14.png" /> Benda<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_15.png" /> Bendung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_16.png" /> Binong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_17.png" /> Binuang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_18.png" /> Bitungjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_19.png" /> Blubuk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_20.png" /> Bojong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_21.png" /> Bojongkamal<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_22.png" /> Bojongloa<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_23.png" /> Bojongnangka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_24.png" /> Bojongrenged<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_25.png" /> Bonisari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_26.png" /> Buaranbambu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_27.png" /> Buaranjati<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_28.png" /> Buaranmangga<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_29.png" /> Budimulya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_30.png" /> Bunar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_31.png" /> Bunder<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_32.png" /> Buniayu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_33.png" /> Cakung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_34.png" /> Cangkudu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_35.png" /> Carenang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_36.png" /> Carenangudik<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_37.png" /> Caringin<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_38.png" /> Cempaka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_39.png" /> Ciakar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_40.png" /> Ciangir<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_41.png" /> Cibadak<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_42.png" /> Cibetok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_43.png" /> Cibodasbaru<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_44.png" /> Cibodassari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_45.png" /> Cibogo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_46.png" /> Cibugel<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_47.png" /> Cibunar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_48.png" /> Cicalengka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_49.png" /> Cidahu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_50.png" /> Cihuni<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_51.png" /> Cijantra<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_52.png" /> Cijeruk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_53.png" /> Cikande<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_54.png" /> Cikareo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_55.png" /> Cikasungka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_56.png" /> Cikuda<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_57.png" /> Cikupa<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_58.png" /> Cikuya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_59.png" /> Cilaku<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_60.png" /> Cileles<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_61.png" /> Cilenggang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_62.png" /> Cipaeh<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_63.png" /> Cirarab<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_64.png" /> Cireundeu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_65.png" /> Cirumpak<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_66.png" /> Cisauk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_67.png" /> Cisereh<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_68.png" /> Cisoka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_69.png" /> Cukanggalih<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_70.png" /> Curug Kulon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_71.png" /> Curug Wetan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_72.png" /> Curugsangerang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_73.png" /> Dadap<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_74.png" /> Dangdang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_75.png" /> Dangdeur<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_76.png" /> Daon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_77.png" /> Daru<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_78.png" /> Dukuh<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_79.png" /> Gaga<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_80.png" /> Gandaria<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_81.png" /> Gandasari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_82.png" /> Gebangraya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_83.png" /> Gelamjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_84.png" /> Gembong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_85.png" /> Gembor<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_86.png" /> Gempolsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_87.png" /> Gintung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_88.png" /> Gintungcilejet<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_89.png" /> Gunungkaler<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_90.png" /> Gunungsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_91.png" /> Jagabita<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_92.png" /> Jambe<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_93.png" /> Jambukarya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_94.png" /> Jatake<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_95.png" /> Jatimulya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_96.png" /> Jatiwaringin<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_97.png" /> Jayanti<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_98.png" /> Jenggot<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_99.png" /> Jengjing<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_100.png" /> Jengkol<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_101.png" /> Kabasiran<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_102.png" /> Kadu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_103.png" /> Kaduagung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_104.png" /> Kadujaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_105.png" /> Kadusirung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_106.png" /> Kaliasin<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_107.png" /> Kamal<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_108.png" /> Kamalmuara<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_109.png" /> Kampungbesar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_110.png" /> Kampungmelayu Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_111.png" /> Kampungmelayu Timur<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_112.png" /> Kandawati<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_113.png" /> Karanganyar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_114.png" /> Karangharja<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_115.png" /> Karangserang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_116.png" /> Karangtengah<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_117.png" /> Karet<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_118.png" /> Kayuagung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_119.png" /> Kayubongkok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_120.png" /> Keboncau<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_121.png" /> Kedaung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_122.png" /> Kedaung Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_123.png" /> Kedaung Wetan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_124.png" /> Kedaungbaru<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_125.png" /> Kedung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_126.png" /> Kedungdalem<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_127.png" /> Kelapadua<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_128.png" /> Kemiri<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_129.png" /> Kemuning<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_130.png" /> Keranggan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_131.png" /> Ketapang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_132.png" /> Kiarapayung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_133.png" /> Klebet<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_134.png" /> Klutuk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_135.png" /> Kohod<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_136.png" /> Koper<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_137.png" /> Kosambi<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_138.png" /> Kosambi Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_139.png" /> Kosambi Dalam<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_140.png" /> Kosambi Timur<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_141.png" /> Kotabumi<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_142.png" /> Kramat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_143.png" /> Kresek<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_144.png" /> Kronjo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_145.png" /> Kubang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_146.png" /> Kutabaru<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_147.png" /> Kutajaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_148.png" /> Kutruk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_149.png" /> Laksana<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_150.png" /> Lebakwangi<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_151.png" /> Legok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_152.png" /> Legoksukamaju<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_153.png" /> Lembangsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_154.png" /> Lemo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_155.png" /> Lengkong Karya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_156.png" /> Lengkong Kulon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_157.png" /> Lengkong Wetan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_158.png" /> Lengkonggudang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_159.png" /> Lontar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_160.png" /> Maja<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_161.png" /> Malangnengah<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_162.png" /> Manisjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_163.png" /> Margamulya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_164.png" /> Margasari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_165.png" /> Mauk Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_166.png" /> Mauk Timur<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_167.png" /> Medang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_168.png" /> Mekarbakti<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_169.png" /> Mekarbaru<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_170.png" /> Mekarjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_171.png" /> Mekarkondang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_172.png" /> Mekarsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_173.png" /> Mekarwangi<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_174.png" /> Merak<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_175.png" /> Muara<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_176.png" /> Muncul<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_177.png" /> Muncung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_178.png" /> Munjul<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_179.png" /> Nyompok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_180.png" /> Onyam<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_181.png" /> Pabuaran<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_182.png" /> Pagedangan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_183.png" /> Pagedangan Ilir<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_184.png" /> Pagedangan Udik<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_185.png" /> Pagenjahan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_186.png" /> Pajang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_187.png" /> Pakualam<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_188.png" /> Pakuhaji<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_189.png" /> Pakulonan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_190.png" /> Pakulonan Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_191.png" /> Palasari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_192.png" /> Pangadegan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_193.png" /> Pangkalan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_194.png" /> Pangkat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_195.png" /> Panongan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_196.png" /> Panunggangan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_197.png" /> Panunggangan Barat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_198.png" /> Parahu<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_199.png" /> Parigi<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_200.png" /> Parungpanjang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_201.png" /> Pasanggrahan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_202.png" /> Pasarkemis<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_203.png" /> Pasilian<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_204.png" /> Pasir<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_205.png" /> Pasirampo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_206.png" /> Pasirbarat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_207.png" /> Pasirbolang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_208.png" /> Pasirgadung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_209.png" /> Pasirgintung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_210.png" /> Pasirjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_211.png" /> Pasirmuncang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_212.png" /> Pasirnangka<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_213.png" /> Patramanggala<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_214.png" /> Patrasana<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_215.png" /> Pedaleman<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_216.png" /> Pekayon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_217.png" /> Pematang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_218.png" /> Periuk<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_219.png" /> Periukjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_220.png" /> Pete<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_221.png" /> Peusar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_222.png" /> Pisanganjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_223.png" /> Pondok Jagung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_224.png" /> Pondokjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_225.png" /> Pondokkelor<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_226.png" /> Racagede<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_227.png" /> Rajeg<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_228.png" /> Rajegmulya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_229.png" /> Rancabango<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_230.png" /> Rancabuaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_231.png" /> Rancagong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_232.png" /> Rancailat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_233.png" /> Rancaiyuh<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_234.png" /> Rancakalapa<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_235.png" /> Rancalabuh<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_236.png" /> Rancasumur<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_237.png" /> Rawaboni<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_238.png" /> Rawaburung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_239.png" /> Rawakidang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_240.png" /> Rawarengas<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_241.png" /> Renged<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_242.png" /> Saga<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_243.png" /> Salembaranjati<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_244.png" /> Salembaranjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_245.png" /> Sampora<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_246.png" /> Sangiang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_247.png" /> Sarakan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_248.png" /> Sasak<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_249.png" /> Selapajang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_250.png" /> Selapajangjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_251.png" /> Sentul<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_252.png" /> Sentuljaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_253.png" /> Sepatan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_254.png" /> Serdang Wetan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_255.png" /> Serdangkulon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_256.png" /> Serpong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_257.png" /> Sidoko<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_258.png" /> Sindangasih<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_259.png" /> Sindangjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_260.png" /> Sindangpanon<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_261.png" /> Sindangsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_262.png" /> Sindangsono<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_263.png" /> Singabangsa<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_264.png" /> Singabraja<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_265.png" /> Situgadung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_266.png" /> Sodong<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_267.png" /> Solear<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_268.png" /> Songgomjaya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_269.png" /> Sukaasih<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_270.png" /> Sukabakti<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_271.png" /> Sukadamai<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_272.png" /> Sukadiri<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_273.png" /> Sukaharja<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_274.png" /> Sukamanah<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_275.png" /> Sukamantri<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_276.png" /> Sukamulya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_277.png" /> Sukamurni<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_278.png" /> Sukanagara<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_279.png" /> Sukasari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_280.png" /> Sukatani<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_281.png" /> Sukawali<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_282.png" /> Sumurbandung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_283.png" /> Suradita<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_284.png" /> Suryabahari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_285.png" /> Taban<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_286.png" /> Talaga<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_287.png" /> Talagasari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_288.png" /> Talok<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_289.png" /> Tamiang<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_290.png" /> Tanahmerah<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_291.png" /> Tanara<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_292.png" /> Tanjakan<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_293.png" /> Tanjakanmekar<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_294.png" /> Tanjunganom<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_295.png" /> Tanjungburung<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_296.png" /> Tanjungpasir<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_297.png" /> Tanjungsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_298.png" /> Tapos<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_299.png" /> Tegalangus<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_300.png" /> Tegalkunir Kidul<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_301.png" /> Tegalkunir Lor<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_302.png" /> Tegalsari<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_303.png" /> Teluknaga<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_304.png" /> Tenjo<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_305.png" /> Tigaraksa<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_306.png" /> Tiparraya<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_307.png" /> Tobat<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_308.png" /> Waliwis<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_309.png" /> Wanakerta<br />\
    <img src="styles/legend/ADMINISTRASIDESA_AR_25K_1_310.png" /> <br />'
        });

lyr_ADMINISTRASI_LN_25K_0.setVisible(true);lyr_ADMINISTRASIDESA_AR_25K_1.setVisible(true);
var layersList = [lyr_ADMINISTRASI_LN_25K_0,lyr_ADMINISTRASIDESA_AR_25K_1];
lyr_ADMINISTRASI_LN_25K_0.set('fieldAliases', {'KARKTR': 'KARKTR', 'STSBTS': 'STSBTS', 'FCODE': 'FCODE', 'KELAS': 'KELAS', 'UUPP': 'UUPP', 'LOKASI': 'LOKASI', 'REMARK': 'REMARK', 'NAMOBJ': 'NAMOBJ', 'ADMIN1': 'ADMIN1', 'ADMIN2': 'ADMIN2', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'WAKLD1': 'WAKLD1', 'WAKLD2': 'WAKLD2', 'WADKC1': 'WADKC1', 'WADKC2': 'WADKC2', 'WAKBK1': 'WAKBK1', 'WAKBK2': 'WAKBK2', 'WAPRO1': 'WAPRO1', 'WAPRO2': 'WAPRO2', 'TIPTBT': 'TIPTBT', 'PJGBTS': 'PJGBTS', 'KLBADM': 'KLBADM', 'TIPLOK': 'TIPLOK', 'SHAPE_Leng': 'SHAPE_Leng', });
lyr_ADMINISTRASIDESA_AR_25K_1.set('fieldAliases', {'KDPPUM': 'KDPPUM', 'NAMOBJ': 'NAMOBJ', 'REMARK': 'REMARK', 'KDPBPS': 'KDPBPS', 'FCODE': 'FCODE', 'LUASWH': 'LUASWH', 'UUPP': 'UUPP', 'SRS_ID': 'SRS_ID', 'LCODE': 'LCODE', 'METADATA': 'METADATA', 'KDEBPS': 'KDEBPS', 'KDEPUM': 'KDEPUM', 'KDCBPS': 'KDCBPS', 'KDCPUM': 'KDCPUM', 'KDBBPS': 'KDBBPS', 'KDBPUM': 'KDBPUM', 'WADMKD': 'WADMKD', 'WIADKD': 'WIADKD', 'WADMKC': 'WADMKC', 'WIADKC': 'WIADKC', 'WADMKK': 'WADMKK', 'WIADKK': 'WIADKK', 'WADMPR': 'WADMPR', 'WIADPR': 'WIADPR', 'TIPADM': 'TIPADM', 'SHAPE_Leng': 'SHAPE_Leng', 'SHAPE_Area': 'SHAPE_Area', });
lyr_ADMINISTRASI_LN_25K_0.set('fieldImages', {'KARKTR': '', 'STSBTS': '', 'FCODE': '', 'KELAS': '', 'UUPP': '', 'LOKASI': '', 'REMARK': '', 'NAMOBJ': '', 'ADMIN1': '', 'ADMIN2': '', 'SRS_ID': '', 'LCODE': '', 'METADATA': '', 'WAKLD1': '', 'WAKLD2': '', 'WADKC1': '', 'WADKC2': '', 'WAKBK1': '', 'WAKBK2': '', 'WAPRO1': '', 'WAPRO2': '', 'TIPTBT': '', 'PJGBTS': '', 'KLBADM': '', 'TIPLOK': '', 'SHAPE_Leng': '', });
lyr_ADMINISTRASIDESA_AR_25K_1.set('fieldImages', {'KDPPUM': 'TextEdit', 'NAMOBJ': 'TextEdit', 'REMARK': 'TextEdit', 'KDPBPS': 'TextEdit', 'FCODE': 'TextEdit', 'LUASWH': 'TextEdit', 'UUPP': 'TextEdit', 'SRS_ID': 'TextEdit', 'LCODE': 'TextEdit', 'METADATA': 'TextEdit', 'KDEBPS': 'TextEdit', 'KDEPUM': 'TextEdit', 'KDCBPS': 'TextEdit', 'KDCPUM': 'TextEdit', 'KDBBPS': 'TextEdit', 'KDBPUM': 'TextEdit', 'WADMKD': 'TextEdit', 'WIADKD': 'TextEdit', 'WADMKC': 'TextEdit', 'WIADKC': 'TextEdit', 'WADMKK': 'TextEdit', 'WIADKK': 'TextEdit', 'WADMPR': 'TextEdit', 'WIADPR': 'TextEdit', 'TIPADM': 'TextEdit', 'SHAPE_Leng': 'TextEdit', 'SHAPE_Area': 'TextEdit', });
lyr_ADMINISTRASI_LN_25K_0.set('fieldLabels', {'KARKTR': 'inline label', 'STSBTS': 'inline label', 'FCODE': 'inline label', 'KELAS': 'inline label', 'UUPP': 'inline label', 'LOKASI': 'inline label', 'REMARK': 'inline label', 'NAMOBJ': 'inline label', 'ADMIN1': 'inline label', 'ADMIN2': 'inline label', 'SRS_ID': 'inline label', 'LCODE': 'inline label', 'METADATA': 'inline label', 'WAKLD1': 'inline label', 'WAKLD2': 'inline label', 'WADKC1': 'inline label', 'WADKC2': 'inline label', 'WAKBK1': 'inline label', 'WAKBK2': 'inline label', 'WAPRO1': 'inline label', 'WAPRO2': 'inline label', 'TIPTBT': 'inline label', 'PJGBTS': 'inline label', 'KLBADM': 'inline label', 'TIPLOK': 'inline label', 'SHAPE_Leng': 'inline label', });
lyr_ADMINISTRASIDESA_AR_25K_1.set('fieldLabels', {'KDPPUM': 'inline label', 'NAMOBJ': 'inline label', 'REMARK': 'inline label', 'KDPBPS': 'inline label', 'FCODE': 'inline label', 'LUASWH': 'inline label', 'UUPP': 'inline label', 'SRS_ID': 'inline label', 'LCODE': 'inline label', 'METADATA': 'inline label', 'KDEBPS': 'inline label', 'KDEPUM': 'inline label', 'KDCBPS': 'inline label', 'KDCPUM': 'inline label', 'KDBBPS': 'inline label', 'KDBPUM': 'inline label', 'WADMKD': 'inline label', 'WIADKD': 'inline label', 'WADMKC': 'inline label', 'WIADKC': 'inline label', 'WADMKK': 'inline label', 'WIADKK': 'inline label', 'WADMPR': 'inline label', 'WIADPR': 'inline label', 'TIPADM': 'inline label', 'SHAPE_Leng': 'inline label', 'SHAPE_Area': 'inline label', });
lyr_ADMINISTRASIDESA_AR_25K_1.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});